"""Research state definitions for the collaborative multi-agent graph."""

from typing import TypedDict, List, Dict, Any, Optional


class ResearchHypothesis(TypedDict, total=False):
    """A single scientific hypothesis generated by the research system."""
    id: str                          # UUID
    title: str                       # One-line summary
    description: str                 # Full hypothesis text
    mechanism: str                   # Underlying mechanism or reasoning
    evidence: List[str]              # Supporting source URLs or citations
    elo_rating: float                # Current ELO score (default 1500)
    round_created: int               # Which round generated this hypothesis
    status: str                      # alive | eliminated | merged | refined
    merged_from: List[str]           # IDs of hypotheses merged to form this one
    critiques: List[Dict[str, Any]]  # Reflection feedback history
    refinement_history: List[str]    # Descriptions of refinements applied


class ResearchState(TypedDict, total=False):
    """LangGraph state for the collaborative research workflow."""

    research_goal: str
    sub_questions: List[str]
    hypotheses: List[ResearchHypothesis]
    current_round: int
    max_rounds: int
    debates_per_round: int
    hypotheses_per_round: int
    parallel_instances: int
    search_results: List[Dict[str, Any]]
    tournament_results: List[Dict[str, Any]]
    code_execution_results: List[Dict[str, Any]]
    final_report: Dict[str, Any]
    errors: List[Dict[str, Any]]
    config: Dict[str, Any]
